name: Publish model to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --find-links https://download.pytorch.org/whl/cpu/torch_stable.html \
            pyyaml huggingface-hub safetensors "torch==2.2.2+cpu" "numpy<2"

      - name: Check for model files
        run: |
          if [ ! -f "src/degdiff/model_def.py" ]; then
            echo "Error: Model definition file src/degdiff/model_def.py not found"
            exit 1
          fi
          if [ ! -f "checkpoints/best.safetensors" ]; then
            echo "Error: Checkpoint file checkpoints/best.safetensors not found"
            exit 1
          fi

      - name: Run publish script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          PYTHONPATH=src python scripts/publish_to_hf.py --config model_publish.yml
